version: '3.9'

services:
  postgres:
    image: mysql:latest
    restart: always
    container_name: stream-wave
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user_id
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: password

    volumes:
      - stream-wave:/var/lib/mysql

volumes:
  stream-wave:
